### ISSUE TITLE
Firefox addon

### ISSUE THREAD

**Issue by profucius** [elblogbruno/NotionAI-MyMind#2]
Hi there, very interested in trying your project. However, it appears you only have an extension for Chrome and not an addon for Firefox? I cannot use Chrome; can only use Firefox. I request that you please release one! Thank you.

**Comment by elblogbruno** [comment]
Hi @profucius the firefox extension it's on the project folder but doesn't know if it works, I need to fix it because it uses APIs from chrome that firefox can't use so I suspect it won't work. Currently can't work on this project expect some delay.
Thanks for your interest!

**Comment by elblogbruno** [comment]
Hi @profucius Firefox extension now works perfectly, go grab the latest release, and tell me if it works!

**Comment by profucius** [comment]
I'll check it out after you submit it to the Firefox add-on store. Thanks!

**Comment by elblogbruno** [comment]
I am waiting for approval from the people at Mozilla!
Cordially

**Comment by elblogbruno** [comment]
Just got approved!
@profucius here you go, and sorry for the long time.

https://addons.mozilla.org/es/android/addon/notion-ai-my-mind/

Hope Firefox folks like it!

**Comment by profucius** [comment]
Is this created for Firefox on Desktop? I look at the addon page and it tells me "This add-on is not available on your platform." on Windows/Desktop.

**Comment by elblogbruno** [comment]
It is meant for firefox on desktop. I need to finish the android and ios app.

**Comment by profucius** [comment]
Right, but what I am saying is that Mozilla is telling me that I cannot download it on desktop. Screenshot attached:

![image](https://user-images.githubusercontent.com/18254607/103158444-f4eb0000-478b-11eb-92a1-d51f0b531e60.png)

**Comment by elblogbruno** [comment]
That's a very strange thing, thanks for pointing that out , I will look into it!

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by elblogbruno** [comment]
@profucius the link is in the photo tells it is an android link. As I have said it is for desktop, windows or mac or Linux firefox installation. 
Please access this link: https://addons.mozilla.org/es/firefox/addon/notion-ai-my-mind/
It is mistaken on the README, I will change it!

**Comment by profucius** [comment]
Oh yes, this makes sense now! I somehow did not even see "android" in the URL before. This worked, I was able to install the addon now. Thanks for clearing that up!

**Comment by elblogbruno** [comment]
I am very glad! Close the issue if you feel so!
