### ISSUE TITLE
& symbol breaks text capture

### ISSUE THREAD

**Issue by profucius** [elblogbruno/NotionAI-MyMind#9]
Found my first bug ;)

I tried capturing text from a page by selecting the text, open context menu, select "Add to my mind". However, the text stopped abruptly at the first & symbol and did not continue. Example below:

Original text:
"Comments    Scientific Frontline said on February 26, 2021 at 8:22 pm    Reply    Well indeed an interesting open-source program.    I personally use several depending on my need.    O&O Diskimage for weekly (or major changes) of all my rigs. (to external HD)"

The resulted page in my mind table:
"Comments    Scientific Frontline said on February 26, 2021 at 8:22 pm    Reply    Well indeed an interesting open-source program.    I personally use several depending on my need.    O"

URL of the original text if you want it, scroll down to the Comments section, first comment: https://www.ghacks.net/2021/02/26/blobbackup-is-an-open-source-cross-platform-and-easy-to-use-backup-program-that-optionally-supports-cloud-services/

**Comment by elblogbruno** [comment]
Hi @profucius I will look into it!

**Comment by elblogbruno** [comment]
I fixed the bug, I will upload a commit soon!
The thing is the text has a & and flask detected it as an argument apart.

**Comment by profucius** [comment]
Fast hunting! Good job I appreciate your hard work
